### ISSUE TITLE
Is getInstance actually needed?

### ISSUE THREAD

**Issue by wilsonge** [joomla-framework/language#12]
I think that getInstance in version 2.0 can be removed. The caching using the debug object is stupid because theoretically you can create two language objects per actual language both with different files loaded etc.

Then if you are only caching based on the language name you may as well hand this off to the user. It could be done in your DI Container or some other place. Not necessarily in the language class

**Comment by eddieajau** [comment]
The method is technically correct, but I agree that the getInstance method is unnecessary so +1 from me.
