### ISSUE TITLE
Joomla\Language\Language.php has references to constant JPATH_ROOT

### ISSUE THREAD

**Issue by purplebeanie** [joomla-framework/language#2]
Hi Folks,

Language.php has some references to constant JPATH_ROOT (mainly in the constructor) that appear to be used in setting some default directories and looking for overrides.

Is this desirable behaviour or should we remove these to make it more stand alone?

Cheers,
Eric.

**Comment by mbabker** [comment]
Closing, this is dealt with in the `2.0-dev` branch.
