### ISSUE TITLE
_QQ_ Mixed with CMS and Framework

### ISSUE THREAD

**Issue by JProof** [joomla-framework/language#36]
Since the Framework grows up, i use it for basic applications and some-times i install the "framework app" into an Joomla installation.

Current:
/**
 * Allows for quoting in language .ini files.
 *
 * @deprecated  2.0
 */
define('_QQ_', '"');

is it possible to check before the define?:
if(!defined('_QQ_')){
        define('_QQ_', '"');
}

**Comment by mbabker** [comment]
Closing.  Moving this is a B/C break and it's gone in the 2.0 branch anyway.
