### ISSUE TITLE
Composer error using joomla/language 2.*

### ISSUE THREAD

**Issue by fastslack** [joomla-framework/language#38]
### Steps to reproduce the issue

1. Add this repo to your own composer.json
```
    "require": {
         "joomla/language": "2.*@dev"
    }
```
2. Try to install your own repo to Joomla! composer.json
```
$ composer require your_own/repo
```
Example:
https://github.com/matware-lab/webservices
https://packagist.org/packages/matware-lab/webservices

### Expected result

The installation of your own repo

### Actual result

    - joomla/language 2.0.x-dev requires php ^5.5.9|~7.0 -> your PHP version (7.0
.13-1+deb.sury.org~trusty+1) overridden by "config.platform.php" version (5.3.10)
 does not satisfy that requirement.

### Possible solution

Set same php version of this repo and joomla repo

**Comment by mbabker** [comment]
The Framework 2.0 branches match the CMS 4.0 minimum requirements described in https://developer.joomla.org/news/658-joomla4-manifesto.html
