### ISSUE TITLE
Joomla\Language\Language.php _QQ_

### ISSUE THREAD

**Issue by fanno** [joomla-framework/language#6]
Hi,
is _QQ_ used for anytging ?

/**
 * Allows for quoting in language .ini files.
 */
define('_QQ_', '"');

i can find any usage of _QQ_ only place it is used as string '_QQ_'.

my issue is that if i try to use Joomla\Language\Language.php inside joomla i get redeclare eror for _QQ_ (OFCAUSE) but it looks that define('_QQ_', '"'); is not used ??

so we might consider having this, or removing _QQ_ ????
if(!defined('_QQ_')) {
     define('_QQ_', '"');
}

-Thanks

**Comment by wilsonge** [comment]
We're dropping it in the CMS so definitely can be dropped from 2.0 forwards

**Comment by infograf768** [comment]
Not dropped yet in CMS though as we have to be B/C.
But, generally speaking:
we can use " for urls and classes
and &quote; in normal text as far as I could test.

What we need to do is refactor the regex in language.php to deal with both.

**Comment by infograf768** [comment]
Just adding that the quotes in text as `"` are ignored in PHP 5.3.+, and therefore need to be html entities
